-- Generated by spritter v0.6.0 - https://github.com/fgardt/factorio-spritter
return {
  ["empty_tank"] = require("empty_tank"),
  ["ring_tank"] = require("ring_tank"),
  ["support_frame"] = require("support_frame"),
}
