-- Generated by spritter v0.6.0 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 111,
  ["line_length"] = 1,
  ["scale"] = 1,
  ["shift"] = {x = 0.5 / 32, y = -0.5 / 32},
  ["sprite_count"] = 1,
  ["width"] = 137,
}
