-- Generated by spritter v0.6.0 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 278,
  ["line_length"] = 1,
  ["scale"] = 0.5,
  ["shift"] = {x = 0 / 64, y = 19 / 64},
  ["sprite_count"] = 1,
  ["width"] = 332,
}
