-- Generated by spritter v0.6.0 - https://github.com/fgardt/factorio-spritter
return {
  ["hr-empty_tank"] = require("hr-empty_tank"),
  ["hr-ring_tank"] = require("hr-ring_tank"),
  ["hr-support_frame"] = require("hr-support_frame"),
}
