-- Generated by spritter v0.6.0 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 110,
  ["line_length"] = 7,
  ["scale"] = 1,
  ["shift"] = {x = 0 / 32, y = -1 / 32},
  ["sprite_count"] = 60,
  ["width"] = 136,
}
