-- Generated by spritter v0.6.0 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 220,
  ["line_length"] = 7,
  ["scale"] = 0.5,
  ["shift"] = {x = -0.5 / 64, y = -1 / 64},
  ["sprite_count"] = 60,
  ["width"] = 271,
}
