-- Generated by spritter v0.6.0 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 257,
  ["line_length"] = 1,
  ["scale"] = 0.5,
  ["shift"] = {x = 0.5 / 64, y = 10.5 / 64},
  ["sprite_count"] = 1,
  ["width"] = 321,
}
