-- Generated by spritter v0.6.0 - https://github.com/fgardt/factorio-spritter
return {
  ["closed"] = require("closed"),
  ["no_window"] = require("no_window"),
  ["reflection"] = require("reflection"),
  ["shadow"] = require("shadow"),
  ["window"] = require("window"),
}
