-- Generated by spritter v0.6.0 - https://github.com/fgardt/factorio-spritter
return {
  ["hr-closed"] = require("hr-closed"),
  ["hr-no_window"] = require("hr-no_window"),
  ["hr-shadow"] = require("hr-shadow"),
  ["hr-window"] = require("hr-window"),
}
