-- Generated by spritter v0.6.0 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 107,
  ["line_length"] = 1,
  ["scale"] = 1,
  ["shift"] = {x = 42.5 / 32, y = 11.5 / 32},
  ["sprite_count"] = 1,
  ["width"] = 77,
}
