-- Generated by spritter v0.6.0 - https://github.com/fgardt/factorio-spritter
return {
  ["height"] = 213,
  ["line_length"] = 1,
  ["scale"] = 0.5,
  ["shift"] = {x = 82.5 / 64, y = 23.5 / 64},
  ["sprite_count"] = 1,
  ["width"] = 157,
}
